const $=id=>document.getElementById(id);let page='library',request=0,currentProfile=null;
function message(text){$('status').textContent=text}
async function api(url,method='GET',data){const res=await fetch(url,{method,headers:{'Content-Type':'application/json','X-Archivist-Action':'1'},body:data?JSON.stringify(data):undefined});if(!(res.headers.get('content-type')||'').includes('application/json'))throw Error('Archivist server response was not available.');const body=await res.json();if(!res.ok)throw Error(body.error||'Request failed');return body}
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
async function loadBooks(){const revision=++request;const items=await api('./api/books?q='+encodeURIComponent($('search').value)+'&space='+encodeURIComponent($('space').value));if(revision!==request)return;$('books').replaceChildren();$('count').textContent=items.length+' files'+(items.length===500?' · First 500 results; narrow your search':'');for(const b of items){const button=element('button');button.className='book';button.dataset.asset=b.id;button.append(Object.assign(element('div',b.title),{className:'cover'}),element('small',b.format+' · '+b.space+(b.author?' · '+b.author:'')+(b.series?' · '+b.series:'')+(b.available?'':' · Unavailable')));button.onclick=()=>{if(!b.available){message('This file was not found on the latest scan.');return}if(b.format==='Audio'){$('playing-title').textContent=b.title;$('audio').src='./api/assets/'+b.id;$('player').hidden=false;$('audio').play().catch(()=>message('Press Play to begin. This browser may not support the audio format.'))}else{window.open('./reader.html?asset='+b.id,'_blank','noopener')}};$('books').append(button)}}
async function loadSources(){const sources=await api('./api/sources');const value=$('space').value;$('space').replaceChildren(new Option('All spaces',''));$('spaces').replaceChildren();for(const name of [...new Set(sources.map(s=>s.space))]){$('space').add(new Option(name,name));$('spaces').append(new Option(name,name))}$('space').value=value;$('source-list').replaceChildren();for(const s of sources){const row=element('article');row.className='source';row.append(element('strong',s.space),element('p',s.path),element('p',s.status));const scan=element('button','Scan folder');scan.onclick=async()=>{scan.disabled=true;message('Scanning '+s.space+'…');try{await api('./api/sources/'+s.id+'/scan','POST');await loadSources();await loadBooks();message('Scan queued. You can keep browsing.');pollJobs()}catch(e){message(e.message)}finally{scan.disabled=false}};const remove=element('button','Remove source');remove.onclick=async()=>{if(!confirm('Remove this source and its catalogue entries? Original files will remain untouched.'))return;try{await api('./api/sources/'+s.id,'DELETE');await loadSources();await loadBooks();message('Source removed. Original files were not changed.')}catch(e){message(e.message)}};row.append(scan,remove);$('source-list').append(row)}}
async function loadConfig(){if(!currentProfile?.owner)return;const [info,sessions]=await Promise.all([api('./api/server-info'),api('./api/sessions')]);$('config-summary').replaceChildren();for(const [label,value] of [['Server address',info.address],['Owner access',info.configured?'Ready':'Not set'],['Source folders',String(info.sources)],['Active scans',String(info.activeJobs)],['Signed-in sessions',String(info.sessions)]]){const row=element('p');row.append(element('strong',label+': '),document.createTextNode(value));$('config-summary').append(row)}if(info.roots?.length){const roots=element('p','Browsable roots: '+info.roots.map(r=>r.name).join(', '));$('config-summary').append(roots)}$('owner-access-save').textContent=info.configured?'Replace access key':'Set access key';$('session-list').replaceChildren();if(!sessions.length)$('session-list').append(element('p','No active sessions.'));for(const s of sessions){const row=element('article');row.className='source';row.append(element('strong','Session '+s.id),element('p','Created '+new Date(s.created*1000).toLocaleString()),element('p','Expires '+new Date(s.expires*1000).toLocaleString()));$('session-list').append(row)}}
async function start(){currentProfile=await api('./api/me');await loadSources();await loadBooks();$('setup').hidden=true;$('unlock').hidden=true;$('nav').hidden=false;show(page);document.querySelector('[data-page="sources"]').hidden=!currentProfile.owner;document.querySelector('[data-page="config"]').hidden=!currentProfile.owner;window.dispatchEvent(new Event('archivist-ready'))}
async function boot(){try{await start()}catch(e){try{const setup=await api('./setup/status');$('setup').hidden=setup.configured;$('unlock').hidden=!setup.configured}catch(err){message(err.message)}}}
function show(next){page=next;for(const p of ['library','sources','config'])$(p).hidden=p!==next;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===next?'page':'false'));message('');if(next==='config')loadConfig().catch(e=>message(e.message))}
$('setup-form').onsubmit=async e=>{e.preventDefault();try{await api('./setup','POST',{token:$('setup-key').value});$('setup-key').value='';await start()}catch(e){message(e.message)}};
$('login').onsubmit=async e=>{e.preventDefault();try{await api('./unlock','POST',{token:$('key').value});$('key').value='';await start()}catch(e){message(e.message)}};
$('owner-access-form').onsubmit=async e=>{e.preventDefault();const button=$('owner-access-save');button.disabled=true;try{const token=$('owner-access-key').value;await api('./api/owner-access','POST',{token});$('owner-access-key').value='';message('Server access key saved. Use it when connecting the Archivist app.');await loadConfig()}catch(e){message(e.message)}finally{button.disabled=false}};
$('add').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('./api/sources','POST',{path:$('path').value,space:$('new-space').value});$('path').value='';await loadSources();message('Folder added. Select Scan folder to catalogue it.')}catch(e){message(e.message)}finally{b.disabled=false}};
let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>loadBooks().catch(e=>message(e.message)),180)};$('space').onchange=()=>loadBooks().catch(e=>message(e.message));document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));$('close-player').onclick=()=>{$('audio').pause();$('audio').removeAttribute('src');$('audio').load();$('player').hidden=true};$('audio').onerror=()=>message('Unable to play this file. Check availability and browser codec support.');
$('theme').value=localStorage.getItem('archivist-theme')||'system';function theme(){document.documentElement.style.colorScheme=$('theme').value==='system'?'light dark':$('theme').value;localStorage.setItem('archivist-theme',$('theme').value)}$('theme').onchange=theme;theme();boot();
let folder='',parent='',jobTimer,jobSignature='';
async function browse(p=''){$('picker').hidden=false;$('folder-location').textContent='Loading folders…';$('folder-items').replaceChildren();$('folder-up').disabled=true;$('folder-use').disabled=true;try{const data=await api('./api/folders?path='+encodeURIComponent(p));folder=data.path||'';parent=data.parent||'';$('folder-location').textContent=folder||'Choose a starting folder';$('folder-up').disabled=!parent;$('folder-use').disabled=!folder;const items=Array.isArray(data.folders)?data.folders:[];for(const f of items){const row=element('div'),name=element('strong',f.name),open=element('button','Open'),use=element('button','Use folder');row.className='source';open.type=use.type='button';open.title='Open '+f.path;use.title='Choose '+f.path;open.onclick=()=>browse(f.path);use.onclick=()=>{$('path').value=f.path;$('picker').hidden=true;message('Folder selected. Choose Add folder to add it to Archivist.')};row.append(name,element('p',f.path),open,use);$('folder-items').append(row)}if(!items.length)$('folder-items').append(element('p','No readable folders are available here.'))}catch(e){folder='';parent='';$('folder-location').textContent='Unable to browse server folders';$('folder-items').replaceChildren(element('p',e.message));message(e.message)}}
const browseButton=element('button','Browse server folders');browseButton.type='button';browseButton.onclick=()=>browse($('path').value);$('add').append(browseButton);$('folder-up').onclick=()=>browse(parent);$('folder-use').onclick=()=>{$('path').value=folder;$('picker').hidden=true};$('folder-close').onclick=()=>{$('picker').hidden=true};
async function pollJobs(){clearTimeout(jobTimer);try{if(!currentProfile?.owner)return;const jobs=await api('./api/jobs');$('scan-jobs').hidden=jobs.length===0;$('jobs').replaceChildren();for(const j of jobs.slice(0,5)){const row=element('div'),label=element('p','Scan '+j.id+' · '+j.state+(j.message?' · '+j.message:''));row.append(label);if(j.state==='queued'||j.state==='running'){const bar=element('progress');bar.max=Math.max(1,j.total||1);bar.value=Math.min(bar.max,j.progress||0);bar.style.width='100%';row.append(bar)}$('jobs').append(row)}const signature=JSON.stringify(jobs);if(signature!==jobSignature){jobSignature=signature;await loadSources();await loadBooks()}}catch(e){if(!$('unlock').hidden)return;message(e.message)}finally{jobTimer=setTimeout(pollJobs,2000)}}pollJobs();
