const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:1,target:9}}).outputText,file);
const {groupLocalWorks}=require('./localWorks.ts');
const {logicalWorkKey}=require('./libraryIntelligence.ts');
const {lookupOnlineBook,hydrateBookCandidate}=require('./onlineBookMetadata.ts');
const app=fs.readFileSync('App.tsx','utf8');
const helper=app.slice(app.indexOf('function reviewBooksForDisplay'),app.indexOf('function Client()'));
const reviewBooksForDisplay=new Function('groupLocalWorks','logicalWorkKey',ts.transpileModule(helper,{compilerOptions:{target:9}}).outputText+';return reviewBooksForDisplay')(groupLocalWorks,logicalWorkKey);
const files=Array.from({length:227},(_,i)=>({id:i,uri:'file:///Books/Author/Book '+(i%12)+'/Chapter '+i+'.mp3',title:'Book '+(i%12),author:'An Author',series:'',format:'Audio',space:'Books',source:'local',needsReview:true}));
assert.equal(reviewBooksForDisplay(files).length,12,'227 chapters must display/count as 12 books');
const start=app.indexOf('const runMetadataSearch=async'),end=app.indexOf('const useProposal=',start);
assert.equal(/persistEditorWork|replaceLocalStageBooks/.test(app.slice(start,end)),false,'search must never save unaccepted drafts');
const modal=app.slice(app.indexOf('    return <Modal transparent',app.indexOf('function MetadataEditorPanel')),app.indexOf('function BulkMetadataPanel'));
assert.ok(modal.lastIndexOf('</ScrollView>')<modal.indexOf("label={busy?'Saving…':'Save'}"),'Save must stay outside scrolling fields');
assert.ok(modal.includes("maxHeight:'100%'")&&modal.includes("keyboardShouldPersistTaps=\"handled\""));
assert.ok(app.includes("const reviewCount=pendingReviewBooks.filter(book=>book.source!=='server').length"),'onboarding must use the same grouped review collection');
assert.ok(modal.indexOf('accessibilityLabel="Corrected title"')<modal.indexOf('<ScrollView'),'title input must stay visible when results change');
assert.ok(modal.includes('Use this book →'),'search results must expose an explicit selection action');
(async()=>{
 const candidate={provider:'openlibrary',providerId:'/works/test',fields:{title:'Dune',author:'Frank Herbert'}};
 const enriched=await hydrateBookCandidate(candidate,{fetcher:async()=>({ok:true,status:200,json:async()=>({description:{value:'A desert planet.'},subjects:['Science fiction']})})});
 assert.equal(enriched.fields.genre,'Science Fiction');
 assert.equal(enriched.fields.description,'A desert planet.');
 assert.equal(enriched.fields.title,'Dune');
 assert.equal(candidate.fields.genre,undefined,'hydration must not mutate the original result');
 const offline=await hydrateBookCandidate(candidate,{fetcher:async()=>{throw Error('offline')}});
 assert.equal(offline,candidate,'detail fetch failure must retain the selectable search result');
 let queries=[];
 const fetcher=async url=>{queries.push(new URL(url).searchParams.get('q'));return {ok:true,status:200,json:async()=>({docs:[{key:'/works/dune',title:'Dune',author_name:['Frank Herbert'],cover_i:1}]})}};
 const author=await lookupOnlineBook({title:'',author:'Frank Herbert',uri:'',format:'Audio'},{fetcher,cache:{},interactive:true});
 assert.equal(queries.length,1);assert.match(queries[0],/author:"Frank Herbert"/);assert.doesNotMatch(queries[0],/title:/);
 assert.equal(author.candidates[0].fields.title,'Dune');assert.equal(author.autoApply,false,'author-only results require a choice');
 queries=[];
 const precise=await lookupOnlineBook({title:'Dune',author:'Frank Herbert',uri:'',format:'Audio'},{fetcher,cache:{},interactive:true});
 assert.equal(queries.length,1);assert.equal(precise.candidates[0].fields.author,'Frank Herbert');
 const fallback=await lookupOnlineBook({title:'Assassinorum Kingmaker Warhammer audiobook',author:'Robert Rath',format:'Audio'},{interactive:true,fetcher:async url=>{
   const q=new URL(url).searchParams.get('q');
   if(q.includes('Warhammer'))throw Error('provider error');
   return {ok:true,status:200,json:async()=>({docs:[{key:'/works/OL28185289W',title:'Assassinorum',author_name:['Robert Rath']}]})};
 }});
 assert.equal(fallback.candidates[0].fields.author,'Robert Rath','relaxed search must survive a failed precise query');
 const savedBody=app.slice(app.indexOf('const save=async()=>',app.indexOf('function MetadataEditorPanel')),app.indexOf('const chooseCoverFromDevice=',app.indexOf('function MetadataEditorPanel')));
 assert.equal(savedBody.includes('setEditing(null)'),false,'Save must keep editor open');
 assert.equal(app.split('{MetadataEditorPanel()}').length-1,1,'editor must mount only once outside tab content');
 assert.ok(app.indexOf('{MetadataEditorPanel()}')>app.indexOf('{CurrentTab()}'),'editor must be outside animated tab content');
 console.log('PASS: grouped review counts, persistent mobile Save, draft-only Smart Search and author/title queries');
})().catch(error=>{console.error(error);process.exitCode=1});
