const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:1,target:9}}).outputText,f);
const {applyManualCluesToWork,acceptBookCandidateForWork}=require('./metadataSearchWorkflow.ts');
const {localWorksForReview,partitionLocalBooksByPublication}=require('./publicationPipeline.ts');
const track={id:1,uri:'file:///Dune/01.mp3',title:'Dune',author:'',series:'',genre:'',format:'Audio',space:'Books',available:true,needsReview:true,embeddedMetadata:{title:'Chapter one',trackNumber:1,discNumber:2},libraryCoverUri:'file:///cover.jpg',livingBookCoverUri:'file:///cover.jpg'};
const clues=applyManualCluesToWork([track],[track.uri],{title:'Dune',author:'Frank Herbert'});
assert.equal(partitionLocalBooksByPublication(clues).published.length,0,'saving clues with artwork must not publish');
assert.equal(clues[0].identificationState,'clues-saved');
const authorOnly=applyManualCluesToWork([track],[track.uri],{title:'',author:'Frank Herbert'});
assert.equal(authorOnly[0].author,'Frank Herbert');
assert.equal(partitionLocalBooksByPublication(authorOnly).published.length,0);
const candidate={provider:'openlibrary',providerId:'/works/dune',fields:{title:'Dune',author:'Frank Herbert'},coverUri:'https://example.org/dune.jpg',score:95,confidence:'high',exactIdentifier:false,reasons:[],query:'Dune'};
const accepted=acceptBookCandidateForWork(clues,[track.uri],candidate);
assert.equal(accepted[0].identificationState,'accepted');
assert.deepEqual(accepted[0].embeddedMetadata,track.embeddedMetadata);
const blocked=partitionLocalBooksByPublication(JSON.parse(JSON.stringify(accepted)));
assert.equal(blocked.published.length,0);
assert.equal(blocked.staged.length,1,'accepted artwork failure remains staged across restart');
const ready=accepted.map(b=>({...b,coverUri:'file:///cached.jpg',libraryCoverUri:'file:///cached.jpg',livingBookCoverUri:'file:///jacket.jpg'}));
assert.equal(partitionLocalBooksByPublication(ready).published.length,1);
const corrected=applyManualCluesToWork(ready,[track.uri],{title:'Dune',author:'Frank Herbert',genre:'Science Fiction'});
assert.equal(partitionLocalBooksByPublication(corrected).published.length,1,'editing established acceptance does not unpublish');
console.log('PASS: production clue/accept/publication lifecycle, restart and chapter protection');

assert.equal(localWorksForReview(accepted)[0].needsReview,true);
assert.match(localWorksForReview(accepted)[0].reviewReason,/cover/);
assert.equal(localWorksForReview(ready)[0].needsReview,false);
const {retainPublishedSnapshots,restorePublishedCatalogue}=require('./publicationPipeline.ts');
const replacement=ready.map(b=>({...b,libraryCoverUri:undefined,livingBookCoverUri:undefined,coverUri:undefined}));
const persistedReplacement=retainPublishedSnapshots(replacement,ready);
assert.equal(restorePublishedCatalogue(JSON.parse(JSON.stringify(persistedReplacement))).length,1,'restart retains last good publication during incomplete replacement');
assert.equal(restorePublishedCatalogue(persistedReplacement)[0].libraryCoverUri,'file:///cached.jpg');
assert.equal(restorePublishedCatalogue(retainPublishedSnapshots([],ready)).length,0,'removed sources are not resurrected');
