const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:1,target:9}}).outputText,f);
const {applyManualCluesToWork,acceptBookCandidateForWork,acceptComicCandidateForWork,editorCoverOverride}=require('./metadataSearchWorkflow.ts');
const {localWorksForReview,partitionLocalBooksByPublication}=require('./publicationPipeline.ts');
const track={id:1,uri:'file:///Dune/01.mp3',title:'Dune',author:'',series:'',genre:'',format:'Audio',space:'Books',available:true,needsReview:true,embeddedMetadata:{title:'Chapter one',trackNumber:1,discNumber:2},libraryCoverUri:'file:///cover.jpg',livingBookCoverUri:'file:///cover.jpg'};
const clues=applyManualCluesToWork([track],[track.uri],{title:'Dune',author:'Frank Herbert'});
assert.equal(partitionLocalBooksByPublication(clues).published.length,0,'saving clues with artwork must not publish');
assert.equal(clues[0].identificationState,'clues-saved');
const authorOnly=applyManualCluesToWork([track],[track.uri],{title:'',author:'Frank Herbert'});
assert.equal(authorOnly[0].author,'Frank Herbert');
assert.equal(partitionLocalBooksByPublication(authorOnly).published.length,0);
const candidate={provider:'openlibrary',providerId:'/works/dune',fields:{title:'Dune',author:'Frank Herbert'},coverUri:'https://example.org/dune.jpg',score:95,confidence:'high',exactIdentifier:false,reasons:[],query:'Dune'};
const accepted=acceptBookCandidateForWork(clues,[track.uri],candidate);
assert.equal(accepted[0].identificationState,'accepted');
assert.deepEqual(accepted[0].embeddedMetadata,track.embeddedMetadata);
assert.equal(partitionLocalBooksByPublication(JSON.parse(JSON.stringify(accepted))).published.length,1,
  'accepted metadata must preserve existing verified cover artwork and publish');
const uncovered={...clues[0],coverUri:undefined,libraryCoverUri:undefined,livingBookCoverUri:undefined};
const acceptedWithoutArtwork=acceptBookCandidateForWork([uncovered],[track.uri],candidate);
const blocked=partitionLocalBooksByPublication(JSON.parse(JSON.stringify(acceptedWithoutArtwork)));
assert.equal(blocked.published.length,0,'remote-only artwork must not publish without a local copy');
assert.equal(blocked.staged.length,1,'accepted artwork failure remains staged across restart');
const manualCover='data:image/png;base64,AQID';
const withManualCover={...clues[0],coverUri:manualCover,libraryCoverUri:manualCover,livingBookCoverUri:manualCover,manualOverride:{coverUri:manualCover}};
const acceptedWithManualCover=acceptBookCandidateForWork([withManualCover],[track.uri],candidate);
assert.equal(acceptedWithManualCover[0].coverUri,manualCover,'Smart Search must not override manually accepted local cover art');
assert.equal(acceptedWithManualCover[0].libraryCoverUri,manualCover,'Library artwork must remain locally cached after candidate acceptance');
assert.equal(acceptedWithManualCover[0].livingBookCoverUri,manualCover,'Living Book artwork must survive a metadata-only edit');
assert.equal(partitionLocalBooksByPublication(acceptedWithManualCover).published.length,1,
 'a real identification with pre-existing artwork must publish immediately rather than vanish into attention');

assert.equal(editorCoverOverride(candidate.coverUri,candidate.coverUri,false),undefined,'provider artwork suggestion must not overwrite verified manual artwork on Save');
assert.equal(editorCoverOverride('file:///picked-cover.jpg',candidate.coverUri,true),'file:///picked-cover.jpg','an explicit user-picked cover must still apply');
const comicCandidate={provider:'metron',providerId:'41',fields:{title:'Space Saga',series:'Space Saga',author:'Artist'},coverUri:candidate.coverUri,score:98,confidence:'high',exactIdentifier:true,reasons:[],query:'Space Saga'};
const comicSource={...withManualCover,uri:'file:///Space-Saga.cbz',format:'Comic',title:'Space Saga',author:'Artist'};
const comicAccepted=acceptComicCandidateForWork([comicSource],[comicSource.uri],comicCandidate);
assert.equal(comicAccepted[0].coverUri,manualCover,'comic candidate acceptance must preserve a verified manual cover');
assert.equal(partitionLocalBooksByPublication(comicAccepted).published.length,1,'comic must remain publishable when its verified cover already exists');
const ready=accepted.map(b=>({...b,coverUri:'file:///cached.jpg',libraryCoverUri:'file:///cached.jpg',livingBookCoverUri:'file:///jacket.jpg'}));
assert.equal(partitionLocalBooksByPublication(ready).published.length,1);
const corrected=applyManualCluesToWork(ready,[track.uri],{title:'Dune',author:'Frank Herbert',genre:'Science Fiction'});
assert.equal(partitionLocalBooksByPublication(corrected).published.length,1,'editing established acceptance does not unpublish');
console.log('PASS: production clue/accept/publication lifecycle, restart and chapter protection');

assert.equal(localWorksForReview(acceptedWithoutArtwork)[0].needsReview,true);
assert.match(localWorksForReview(acceptedWithoutArtwork)[0].reviewReason,/cover/);
assert.equal(localWorksForReview(ready)[0].needsReview,false);
const {retainPublishedSnapshots,restorePublishedCatalogue}=require('./publicationPipeline.ts');
const replacement=ready.map(b=>({...b,libraryCoverUri:undefined,livingBookCoverUri:undefined,coverUri:undefined}));
const persistedReplacement=retainPublishedSnapshots(replacement,ready);
assert.equal(restorePublishedCatalogue(JSON.parse(JSON.stringify(persistedReplacement))).length,1,'restart retains last good publication during incomplete replacement');
assert.equal(restorePublishedCatalogue(persistedReplacement)[0].libraryCoverUri,'file:///cached.jpg');
assert.equal(restorePublishedCatalogue(retainPublishedSnapshots([],ready)).length,0,'removed sources are not resurrected');
