const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),sqlite=require('./test-support/sqlite-port.cjs');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {createScannerPipeline}=require('./scannerVNext/pipeline.ts');
(async()=>{const tmp=fs.mkdtempSync(path.join(__dirname,'.scanner-store-test-')),db=sqlite(path.join(tmp,'pipeline.db'));try{
 let id=0,reads=0,searches=0;const source={id:'root',name:'Generated',rootUri:'content://fixture/tree/root'};
 const pipeline=await createScannerPipeline(db,()=>`fixture-${++id}`,{access:{async nextBatch(){return {entries:[1,2,3].map(i=>({documentId:`part${i}`,relativePath:`Generated Novel/Disc 1/Chapter ${i}.mp3`,name:`Chapter ${i}.mp3`,size:100,modified:10})),nextCursor:null};}},async clues(){reads++;return {title:'Generated Novel',author:'Fixture Writer',genre:'Space opera'};}});
 const first=await pipeline.scan(source);assert.equal(first.summary.accounted,3);assert.equal(first.works.length,1);assert.equal(first.works[0].work.partIds.length,3);assert.equal(first.works[0].needsAttention,true);assert.equal(reads,1);
 const work=first.works[0].work;const saved=await pipeline.metadata.saveManual(work.workId,{title:'Approved Novel',author:'Manual Writer',genre:'Fantasy'},0);
 const second=await pipeline.scan(source);assert.equal(second.works[0].work.workId,work.workId);assert.equal(second.works[0].work.fields.author,'Manual Writer');assert.equal(second.works[0].work.fields.genre,'Fantasy');
 const restarted=await createScannerPipeline(db,()=>`fixture-${++id}`,{access:{async nextBatch(){throw new Error('permission lost');}}});const lost=await restarted.scan(source);assert.equal(lost.summary.complete,false);assert.equal(lost.works.length,1);assert.equal(lost.works[0].needsAttention,true);assert.equal(lost.works[0].work.fields.title,'Approved Novel');
 const malformed=await createScannerPipeline(db,()=>`fixture-${++id}`,{access:{async nextBatch(){return {entries:[{documentId:'bad',relativePath:'Malformed.mp3',name:'Malformed.mp3'}],nextCursor:null};}},async clues(){return {title:'x'.repeat(4096),genre:'g'.repeat(4096)};}});const damaged=await malformed.scan({...source,id:'bad',rootUri:'content://fixture/tree/bad'});assert.equal(damaged.summary.accounted,1);assert.equal(damaged.works.length,1);assert.equal(damaged.works[0].needsAttention,true);assert.ok(damaged.works[0].issues.includes('invalid-clue-field'));
 const nonbooks=await createScannerPipeline(db,()=>`fixture-${++id}`,{access:{async nextBatch(){return {entries:['.nomedia','.database_uuid','position.sabp.dat','playlist.m3u','guide.docx','Novel/Opening.mp3','Novel/Ending.mp3'].map((relativePath,i)=>({documentId:'real-shape-'+i,relativePath,name:relativePath.split('/').at(-1)})),nextCursor:null};}}});
 const filtered=await nonbooks.scan({...source,id:'nonbooks'});assert.equal(filtered.summary.accounted,7);assert.equal(filtered.works.length,1,'Phone support files are accounted but must not become books');assert.equal(filtered.works[0].work.partIds.length,2);
 assert.equal(searches,0);console.log('PASS: fresh discovery/grouping/clue pipeline, bounded malformed metadata, one multipart work, manual preservation and visible source recovery');
}finally{await db.close();fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
