const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),sqlite=require('./test-support/sqlite-port.cjs');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {createMetadataStore}=require('./scannerVNext/fieldEvidence.ts'),{createAssistController}=require('./scannerVNext/assist.ts');
(async()=>{
 const tmp=fs.mkdtempSync(path.join(__dirname,'.scanner-store-test-')),db=sqlite(path.join(tmp,'assist.db'));
 try{
  const store=await createMetadataStore(db);await store.ensure({workId:'work',revision:0,fields:{title:'Generated Novel'},manual:{},identityConfirmed:false,partIds:['a','b']});
  let release,calls=0;const service={async search(work,policy){calls++;assert.equal(work.fields.author,'Fixture Writer');return new Promise(resolve=>{release=resolve;});}};
  const assist=await createAssistController(db,store,service);const saved=await assist.save('work',{author:'Fixture Writer'},0,{online:true,automatic:true});assert.equal(saved.work.revision,1);assert.equal(calls,1);assert.equal((await store.get('work')).manual.author,true);assert.equal((await assist.get('work')).state,'pending');
  await store.saveManual('work',{genre:'Fantasy'},1);
  release({state:'review',candidates:[],requests:2,cacheHit:false,issues:[],nextPages:{}});assert.equal((await saved.completion).state,'stale');assert.equal((await store.get('work')).fields.genre,'Fantasy');
  const offline=await createAssistController(db,store,{async search(){return {state:'offline',candidates:[],requests:0,cacheHit:false,issues:[],nextPages:{}};}});const second=await offline.save('work',{title:'Corrected title'},2,{online:false,automatic:true});await second.completion;assert.equal((await offline.get('work')).state,'offline');assert.equal((await store.get('work')).fields.title,'Corrected title');
  let rejectOld,lookupCount=0;const race=await createAssistController(db,store,{async search(){if(++lookupCount===1)return new Promise((resolve,reject)=>{rejectOld=reject;});return {state:'review',candidates:[],requests:1,cacheHit:false,issues:[],nextPages:{}};}});const older=await race.search('work',{online:true,automatic:true}),newest=await race.search('work',{online:true,automatic:true});await newest.completion;rejectOld(new Error('Cancelled older lookup'));await older.completion;assert.equal((await race.get('work')).state,'review');
  let releasePage,pageLookups=0;const paging=await createAssistController(db,store,{async search(){return {state:++pageLookups===1?'review':'no-match',candidates:[],requests:1,cacheHit:false,issues:[],nextPages:{'open-library':1},nextPlans:{'open-library':1}};},async more(work,provider,page,policy,plan){assert.equal(plan,1);return new Promise(resolve=>{releasePage=resolve;});}});await (await paging.search('work',{online:true,automatic:true})).completion;const oldPage=paging.more('work','open-library',1,3,{online:true,automatic:true});while(!releasePage)await new Promise(r=>setTimeout(r,0));await (await paging.search('work',{online:true,automatic:true})).completion;releasePage({state:'review',candidates:[],requests:1,cacheHit:false,issues:[],nextPages:{'open-library':2}});await assert.rejects(oldPage,/Stale/);assert.equal((await paging.get('work')).state,'no-match');
  console.log('PASS: Save persists first, asynchronous work lookup, stale completion/paging rejection, same-revision ownership and offline edits visible');
 }finally{await db.close();fs.rmSync(tmp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
