const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {normalizeGenre,TAXONOMY}=require('./scannerVNext/genre.ts'),{buildPublishedGenreCounts,projectCatalogue}=require('./scannerVNext/projection.ts');
for(const raw of ['', 'Other','Unknown','Fiction','Nonfiction','Audio','Comic','EPUB','SF'])assert.equal(normalizeGenre([{value:raw,source:'provider'}]).state,'unresolved',raw);
assert.equal(normalizeGenre([{value:'Space opera',source:'embedded'}]).label,'Science Fiction');
assert.equal(normalizeGenre([{value:'Science Fiction / Military',source:'provider'}]).label,'Science Fiction');
assert.equal(normalizeGenre([{value:'Dark fantasy',source:'provider'}]).label,'Fantasy');
assert.equal(normalizeGenre([{value:'Fantasy',source:'embedded'},{value:'History',source:'provider'}]).state,'unresolved');
assert.equal(normalizeGenre([{value:'Fantasy',source:'manual'},{value:'History',source:'provider'}]).label,'Fantasy');
assert.equal(normalizeGenre([{value:'invalid-id',source:'manual'}]).state,'unresolved');
const genre=normalizeGenre([{value:'Fantasy',source:'manual'}]),row=(workId,editionId,published=true)=>({workId,editionId,published,revision:1,title:'Fixture',genre,parts:['a','b']});
const rows=[row('one','e1'),row('one','e2'),row('two','e3'),row('staged','e4',false)];
const counts=buildPublishedGenreCounts(rows);assert.equal(counts.total,2);assert.equal(counts.primary.fantasy,2);assert.equal(Object.values(counts.primary).reduce((a,b)=>a+b,0),2);assert.equal(counts.coverage,1);
const visible=projectCatalogue(rows);assert.equal(visible.length,3);assert.equal(visible.find(x=>x.workId==='staged').needsAttention,true);
const recovery=projectCatalogue([row('one','accepted'),{...row('one','pending',false),revision:2,genre:normalizeGenre([{value:'Other',source:'manual'}])}]);assert.equal(recovery.length,1);assert.equal(recovery[0].published,true);assert.equal(recovery[0].genre.label,'Fantasy');assert.equal(recovery[0].needsAttention,true);assert.equal(recovery[0].stagedRevision.revision,2);
assert.throws(()=>buildPublishedGenreCounts([{...row('bad','bad'),genre:normalizeGenre([])}]),/meaningful genre/);
assert.throws(()=>buildPublishedGenreCounts([{...row('bad','bad'),genre:{...genre,id:'invented'}}]),/meaningful genre/);
assert.equal(new Set(TAXONOMY.map(x=>x.id)).size,TAXONOMY.length);
assert.equal(buildPublishedGenreCounts([row('one','old'),{...row('one','new'),revision:2,genre:normalizeGenre([{value:'History',source:'manual'}])}]).primary.history,1);
console.log('PASS: meaningful canonical genres, conflicting evidence, protected manual choice, staged visibility and work-level Atlas totals');
