const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const {randomUUID}=require('node:crypto');
const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
assert.ok(fs.existsSync(path.join(__dirname,'scannerVNext/store.ts')),'New durable scanner store must exist');
const {createScannerStore}=require('./scannerVNext/store.ts');
assert.ok(fs.existsSync(path.join(__dirname,'scannerVNext/groupingStore.ts')),'Atomic grouping snapshot store must exist');
const {createGroupingStore}=require('./scannerVNext/groupingStore.ts');
assert.ok(fs.existsSync(path.join(__dirname,'scannerVNext/clueCache.ts')),'Versioned embedded-clue cache must exist');
const {createClueCache}=require('./scannerVNext/clueCache.ts');
const {groupCandidates}=require('./scannerVNext/grouping.ts');
const python=process.env.SCANNER_TEST_PYTHON||'python3';
function sqlite(file){
  const child=spawn(python,[path.join(__dirname,'test-support/sqlite-bridge.py'),file]);
  const pending=new Map();let id=0;
  createInterface({input:child.stdout}).on('line',line=>{const result=JSON.parse(line);const p=pending.get(result.id);pending.delete(result.id);result.error?p.reject(new Error(result.error)):p.resolve(result.value);});
  child.on('error',error=>{for(const p of pending.values())p.reject(error);});
  child.on('exit',code=>{if(pending.size)for(const p of pending.values())p.reject(new Error('SQLite bridge exited '+code));});
  const request=(operation,sql='',params=[])=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});child.stdin.write(JSON.stringify({id:key,operation,sql,params})+'\n');});
  const db={execAsync:sql=>request('exec',sql),runAsync:(sql,...params)=>request('run',sql,params),getFirstAsync:async(sql,...params)=>(await request('query',sql,params))[0]??null,
    async withExclusiveTransactionAsync(action){await request('run','BEGIN IMMEDIATE');try{const result=await action(db);await request('run','COMMIT');return result;}catch(error){await request('run','ROLLBACK');throw error;}},
    close:()=>request('close')};
  return db;
}
(async()=>{
  const tmp=fs.mkdtempSync(path.join(__dirname,'.scanner-store-test-'));const file=path.join(tmp,'test.db');
  let db=sqlite(file);
  try{
    await db.execAsync("CREATE TABLE local_assets(uri TEXT PRIMARY KEY,payload TEXT); INSERT INTO local_assets VALUES('manual://accepted','protected');");
    let store=await createScannerStore(db,randomUUID);
    await store.saveSource({id:'a',rootUri:'content://a',name:'A'});
    const entry={documentId:'doc-1',relativePath:'one.mp3',name:'one.mp3',mimeType:'audio/mpeg',disposition:{state:'candidate',kind:'audio',reason:'audio-content-unconfirmed',audiobookConfirmed:false}};
    await store.saveBatch('a',[entry],{cursor:'page-2',visited:1,accounted:1,complete:false});
    const original=await store.loadAsset('a','doc-1');assert.ok(original.assetId);assert.equal(original.relativePath,'one.mp3');
    await assert.rejects(store.saveSource({id:'a',rootUri:'content://different-root',name:'Changed'}),/source.*root/i);
    assert.equal((await db.getFirstAsync('SELECT root_uri FROM scanner_vnext_sources WHERE id=?','a')).root_uri,'content://a');
    assert.equal((await store.loadAsset('a','doc-1')).assetId,original.assetId);
    await store.saveSource({id:'a',rootUri:'content://a',name:'Renamed source'});
    assert.equal((await db.getFirstAsync('SELECT name FROM scanner_vnext_sources WHERE id=?','a')).name,'Renamed source');
    await db.close();db=sqlite(file);store=await createScannerStore(db,randomUUID);
    assert.deepEqual(await store.loadCheckpoint('a'),{cursor:'page-2',visited:1,accounted:1,complete:false});
    await store.saveBatch('a',[{...entry,name:'renamed.mp3',relativePath:'renamed.mp3'}],{cursor:null,visited:1,accounted:1,complete:true});
    assert.equal((await store.loadAsset('a','doc-1')).assetId,original.assetId);
    assert.equal((await store.loadAsset('a','doc-1')).relativePath,'renamed.mp3');
    await store.saveSource({id:'b',rootUri:'content://b',name:'B'});
    await store.saveBatch('b',[entry],{cursor:null,visited:1,accounted:1,complete:true});
    assert.notEqual((await store.loadAsset('b','doc-1')).assetId,original.assetId);
    const prior=await store.loadCheckpoint('a');
    await assert.rejects(store.saveBatch('a',[{...entry,documentId:'doc-2'},{...entry,documentId:''}],{cursor:'bad',visited:3,accounted:3,complete:false}),/document ID/);
    assert.equal(await store.loadAsset('a','doc-2'),null);assert.deepEqual(await store.loadCheckpoint('a'),prior);
    const controller=new AbortController();controller.abort();
    await assert.rejects(store.saveBatch('a',[{...entry,documentId:'late'}],prior,controller.signal),/cancelled/);
    assert.equal(await store.loadAsset('a','late'),null);
    const during=new AbortController();
    const interrupted=await createScannerStore({...db,withExclusiveTransactionAsync:action=>db.withExclusiveTransactionAsync(tx=>action({...tx,runAsync:async(sql,...params)=>{const value=await tx.runAsync(sql,...params);if(sql.startsWith('INSERT INTO scanner_vnext_assets'))during.abort();return value;}}))},randomUUID);
    await assert.rejects(interrupted.saveBatch('a',[{...entry,documentId:'during'}],prior,during.signal),/cancelled/);
    assert.equal(await store.loadAsset('a','during'),null);assert.deepEqual(await store.loadCheckpoint('a'),prior);
    await store.saveIssue('a',{reason:'provider-error',detail:'permission revoked',cursor:'p2'});
    assert.equal((await db.getFirstAsync('SELECT reason FROM scanner_vnext_issues')).reason,'provider-error');
    assert.equal((await db.getFirstAsync('SELECT payload FROM local_assets')).payload,'protected');
    let grouping=await createGroupingStore(db,randomUUID);
    const proposal=groupCandidates([{assetId:original.assetId,sourceId:'a',relativePath:'renamed.mp3',kind:'audio'}]);
    const snapshot=await grouping.commitGrouping('a',proposal,0);
    assert.equal(snapshot.revision,1);assert.equal(snapshot.groups[0].parts[0].assetId,original.assetId);
    await assert.rejects(grouping.commitGrouping('a',proposal,0),/Stale grouping revision/);
    assert.equal((await grouping.loadGrouping('a')).revision,1);
    await assert.rejects(grouping.commitGrouping('a',[{...proposal[0],parts:[{assetId:'nonexistent',relativePath:'bad.mp3'}]}],1),/Asset outside selected source/);
    assert.equal((await grouping.loadGrouping('a')).revision,1);
    await db.close();db=sqlite(file);grouping=await createGroupingStore(db,randomUUID);
    assert.deepEqual(await grouping.loadGrouping('a'),snapshot);
    const updated=await grouping.commitGrouping('a',proposal,1);
    assert.equal(updated.groups[0].workId,snapshot.groups[0].workId);assert.equal(updated.revision,2);
    const missing=await grouping.commitGrouping('a',[],2);
    assert.equal(missing.groups[0].workId,snapshot.groups[0].workId);assert.equal(missing.groups[0].parts.length,1);assert.ok(missing.groups[0].issues.includes('source-parts-missing'));
    const cancelledGrouping=new AbortController();cancelledGrouping.abort();
    await assert.rejects(grouping.commitGrouping('a',proposal,3,cancelledGrouping.signal),/cancelled/);
    assert.equal((await grouping.loadGrouping('a')).revision,3);
    let cache=await createClueCache(db);
    const fingerprint={documentId:'doc-1',size:100,modified:1};
    const clues={readerVersion:'header-1',provenance:'embedded',status:'parsed',reason:'id3-header',fields:{album:'A novel',genre:'Fantasy'}};
    await cache.save(original.assetId,fingerprint,clues);
    assert.deepEqual(await cache.load(original.assetId,fingerprint),clues);
    assert.equal(await cache.load(original.assetId,{...fingerprint,size:101}),null);
    assert.equal(await cache.load(original.assetId,{...fingerprint,documentId:'renamed-provider-id'}),null);
    assert.equal(await cache.load(original.assetId,{...fingerprint,modified:null}),null);
    assert.equal(await cache.save(original.assetId,{...fingerprint,modified:null},clues),false);
    await assert.rejects(cache.save(original.assetId,fingerprint,{...clues,readerVersion:'old'}),/version/);
    await assert.rejects(cache.save(original.assetId,fingerprint,{...clues,fields:{title:'x'.repeat(4097)}}),/budget/);
    const cancelledCache=new AbortController();cancelledCache.abort();
    await assert.rejects(cache.save(original.assetId,fingerprint,{...clues,fields:{album:'Late'}},cancelledCache.signal),/cancelled/);
    const duringCache=new AbortController();
    const interruptedCache=await createClueCache({...db,withExclusiveTransactionAsync:action=>db.withExclusiveTransactionAsync(tx=>action({...tx,runAsync:async(sql,...params)=>{const value=await tx.runAsync(sql,...params);if(sql.startsWith('INSERT INTO scanner_vnext_clue_cache'))duringCache.abort();return value;}}))});
    await assert.rejects(interruptedCache.save(original.assetId,fingerprint,{...clues,fields:{album:'Interrupted'}},duringCache.signal),/cancelled/);
    assert.deepEqual(await cache.load(original.assetId,fingerprint),clues);
    await db.close();db=sqlite(file);cache=await createClueCache(db);
    assert.deepEqual(await cache.load(original.assetId,fingerprint),clues);
    await db.execAsync("WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<2001) INSERT INTO scanner_vnext_clue_cache SELECT 'old-'||x,'old','header-1','header64k','{}',0 FROM n;");
    await cache.save(original.assetId,fingerprint,clues);
    assert.equal((await db.getFirstAsync('SELECT COUNT(*) AS count FROM scanner_vnext_clue_cache')).count,2000);
    assert.deepEqual(await cache.load(original.assetId,fingerprint),clues);
    assert.equal((await db.getFirstAsync('SELECT payload FROM local_assets')).payload,'protected');
    console.log('PASS: real SQLite restart, source/root and manual protections, atomic checkpoints and versioned fingerprint-sensitive clue cache');
  }finally{await db.close();fs.rmSync(tmp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
