const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
assert.ok(fs.existsSync(__dirname+'/scannerVNext/grouping.ts'),'Fresh evidence-based grouping module must exist');
const {groupCandidates}=require('./scannerVNext/grouping.ts');
assert.ok(fs.existsSync(__dirname+'/scannerVNext/identity.ts'),'Immutable work/edition reconciliation must exist');
const {reconcileIdentities}=require('./scannerVNext/identity.ts');
const asset=(id,path,kind='audio')=>({assetId:id,sourceId:'s',relativePath:path,kind});
const group=(assets,evidence={})=>groupCandidates(assets,evidence);
let result=group([asset('a','Writer - Example Novel - 10 - Chapter Ten.mp3'),asset('b','Writer - Example Novel - 2 - Chapter Two.mp3')]);
assert.equal(result.length,1);assert.deepEqual(result[0].parts.map(p=>p.assetId),['b','a']);assert.equal(result[0].needsAttention,true);
result=group([asset('a','Series/Series [01] First Novel [01]/Series [01] First Novel [01-02].mp3'),asset('b','Series/Series [01] First Novel [02]/Series [01] First Novel [02-01].mp3'),asset('c','Series/Series [02] Second Novel [01]/Series [02] Second Novel [01-01].mp3')]);
assert.equal(result.length,2);assert.deepEqual(result.map(g=>g.parts.length).sort(),[1,2]);
result=group([asset('a','One Novel/Disc 2/01 - chapter.mp3'),asset('b','One Novel/Disc 1/10 - chapter.mp3')]);
assert.equal(result.length,1);assert.deepEqual(result[0].parts.map(p=>p.assetId),['b','a']);
result=group([asset('a','Book/part 1/Whole Part.m4b'),asset('b','Book/part 2/001_ABBREV02P01.mp3')]);assert.equal(result.length,1);assert.ok(result[0].needsAttention);assert.ok(result[0].issues.includes('missing-part-number'));
result=group([asset('a','Named Book/ABBREVP01.mp3'),asset('b','Named Book/ABBREVP02.mp3')]);assert.equal(result.length,1);assert.ok(result[0].needsAttention);
result=group([asset('a','Author/01 - Whole Novel Alpha.m4b'),asset('b','Author/02 - Whole Novel Beta.m4b')]);assert.equal(result.length,2);
result=group([asset('a','Comics/Issue 1.cbz','comic'),asset('b','Comics/Issue 2.cbz','comic')]);assert.equal(result.length,2);
result=group([asset('a','Unknown/01.mp3'),asset('b','Unknown/02.mp3')]);assert.equal(result.length,2);assert.ok(result.every(g=>g.needsAttention));
result=group([asset('a','Novel/Chapter 1.mp3'),asset('b','Novel/Chapter 1 copy.mp3')]);assert.equal(result.length,1);assert.ok(result[0].issues.includes('duplicate-part-number'));
result=group([asset('a','Edition A/Chapter 1.mp3'),asset('b','Edition B/Chapter 2.mp3')],{a:{title:'Same Work',author:'Writer',edition:'Narrator A',provenance:'embedded'},b:{title:'Same Work',author:'Writer',edition:'Narrator B',provenance:'embedded'}});assert.equal(result.length,2);
result=group([asset('a','Edition A/Chapter 1.mp3'),asset('b','Edition B/Chapter 2.mp3')],{a:{title:'Same Work',author:'Writer',provenance:'embedded'},b:{title:'Same Work',author:'Writer',provenance:'embedded'}});assert.equal(result.length,2,'Unknown editions must not merge on title/author alone');
result=group([asset('a','Novel/Chapter 1.mp3'),asset('b','Novel/Chapter 2.mp3')],{a:{title:'Alpha',author:'One',provenance:'embedded'},b:{title:'Beta',author:'Two',provenance:'embedded'}});assert.equal(result.length,2);
result=group([asset('a','Rename/new.mp3'),asset('b','Rename/other.mp3')],{a:{manualWorkId:'saved-work',manualEditionId:'saved-edition',disc:2,track:1,provenance:'human_confirmed'},b:{manualWorkId:'saved-work',manualEditionId:'saved-edition',disc:1,track:10,provenance:'human_confirmed'}});assert.equal(result.length,1);assert.equal(result[0].priorWorkId,'saved-work');assert.deepEqual(result[0].parts.map(p=>p.assetId),['b','a']);
result=group([asset('a','Novel/Chapter 1.mp3'),asset('b','Novel/Chapter 2.mp3')],{a:{manualWorkId:'split-a',provenance:'human_confirmed'},b:{manualWorkId:'split-b',provenance:'human_confirmed'}});assert.equal(result.length,2);
const shuffled=group([asset('b','One Novel/Chapter 10.mp3'),asset('a','One Novel/Chapter 2.mp3')]);assert.deepEqual(shuffled,group([asset('a','One Novel/Chapter 2.mp3'),asset('b','One Novel/Chapter 10.mp3')]));
assert.throws(()=>group([asset('a','1.mp3'),asset('a','2.mp3')]),/Duplicate asset ID/);
let sequence=0;const newId=()=>String(++sequence);
const first=reconcileIdentities(group([asset('a','Old/Chapter 1.mp3'),asset('b','Old/Chapter 2.mp3')]),[],newId);
const renamed=reconcileIdentities(group([asset('a','Renamed/Chapter 1.mp3'),asset('b','Renamed/Chapter 2.mp3')]),first,newId);
assert.equal(renamed[0].workId,first[0].workId);assert.equal(renamed[0].editionId,first[0].editionId);
const manual=reconcileIdentities(group([asset('a','Renamed/1.mp3'),asset('b','Renamed/2.mp3')],{a:{manualWorkId:'protected',manualEditionId:'edition',provenance:'human_confirmed'},b:{manualWorkId:'protected',manualEditionId:'edition',provenance:'human_confirmed'}}),renamed,newId);
assert.throws(()=>reconcileIdentities(group([asset('a','Renamed/1.mp3'),asset('b','Renamed/2.mp3')]),manual,newId),/Manual grouping is protected/);
const split=reconcileIdentities(group([asset('a','Renamed/1.mp3'),asset('b','Renamed/2.mp3')],{a:{manualWorkId:'split-one',manualEditionId:'one',provenance:'human_confirmed'},b:{manualWorkId:'split-two',manualEditionId:'two',provenance:'human_confirmed'}}),manual,newId);assert.deepEqual(split.map(g=>g.workId).sort(),['split-one','split-two']);
const start=performance.now();const large=group(Array.from({length:100000},(_,i)=>asset(String(i),'Large Novel/Chapter '+(100000-i)+'.mp3')));
assert.equal(large.length,1);assert.equal(large[0].parts.length,100000);assert.equal(large[0].parts[0].track,1);assert.equal(large[0].parts.at(-1).track,100000);
const identified=reconcileIdentities(large,[],newId);assert.equal(reconcileIdentities(large,identified,newId)[0].workId,identified[0].workId);
console.log('PASS: 100,000-part ordering and identity reconciliation, '+Math.round(performance.now()-start)+'ms');
console.log('PASS: loose root, nested series, discs, numeric whole novels, comics, ambiguous numeric tracks, duplicate numbers, editions, conflicting evidence, protected manual merge/split and deterministic ordering');
