const $=id=>document.getElementById(id);let page='library',request=0,currentProfile=null;
function message(text){$('status').textContent=text}
function activity(label,detail='',current=null,total=null){
  const box=$('activity'),bar=$('activity-progress');
  if(!label){box.hidden=true;bar.removeAttribute('value');bar.removeAttribute('max');return}
  box.hidden=false;$('activity-label').textContent=label;$('activity-detail').textContent=detail?(' · '+detail):'';
  if(Number.isFinite(current)&&Number.isFinite(total)&&total>0){bar.max=total;bar.value=Math.min(total,current)}else{bar.removeAttribute('value');bar.removeAttribute('max')}
}
async function api(url,method='GET',data){const res=await fetch(url,{method,headers:{'Content-Type':'application/json','X-Archivist-Action':'1'},body:data?JSON.stringify(data):undefined});if(!(res.headers.get('content-type')||'').includes('application/json'))throw Error('Archivist server response was not available.');const body=await res.json();if(!res.ok)throw Error(body.error||'Request failed');return body}
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
async function loadBooks(){const revision=++request;const items=await api('./api/books?q='+encodeURIComponent($('search').value)+'&space='+encodeURIComponent($('space').value));if(revision!==request)return;$('books').replaceChildren();$('count').textContent=items.length+' files'+(items.length===500?' · First 500 results; narrow your search':'');for(const b of items){const button=element('button');button.className='book';button.dataset.asset=b.id;button.append(Object.assign(element('div',b.title),{className:'cover'}),element('small',b.format+' · '+b.space+(b.author?' · '+b.author:'')+(b.series?' · '+b.series:'')+(b.available?'':' · Unavailable')));button.onclick=()=>{if(!b.available){message('This file was not found on the latest scan.');return}if(b.format==='Audio'){$('playing-title').textContent=b.title;$('audio').src='./api/assets/'+b.id;$('player').hidden=false;$('audio').play().catch(()=>message('Press Play to begin. This browser may not support the audio format.'))}else{window.open('./reader.html?asset='+b.id,'_blank','noopener')}};$('books').append(button)}}
async function loadSources(){const sources=await api('./api/sources');const value=$('space').value;$('space').replaceChildren(new Option('All spaces',''));$('spaces').replaceChildren();for(const name of [...new Set(sources.map(s=>s.space))]){$('space').add(new Option(name,name));$('spaces').append(new Option(name,name))}$('space').value=value;$('source-list').replaceChildren();if(!sources.length){const empty=element('div');empty.className='empty-state';empty.append(element('strong','No source folders yet'),element('p','Choose a folder above to start building your library.'));$('source-list').append(empty)}for(const s of sources){const row=element('article');row.className='source source-card';const head=element('div');head.className='source-head';const title=element('div');title.append(element('strong',s.space),element('p',s.path));const state=element('span',s.status||'Not scanned');state.className='status-pill';head.append(title,state);const actions=element('div');actions.className='source-actions';const scan=element('button','Scan / refresh');scan.className='primary';scan.onclick=async()=>{scan.disabled=true;scan.textContent='Starting scan…';activity('Starting scan',s.space);message('Scanning '+s.space+'…');try{await api('./api/sources/'+s.id+'/scan','POST');message('Scan started. Progress is shown below.');pollJobs()}catch(e){message(e.message)}finally{activity('');scan.disabled=false;scan.textContent='Scan / refresh'}};const remove=element('button','Remove');remove.className='danger-quiet';remove.onclick=async()=>{if(!confirm('Remove this source and its catalogue entries? Original files will remain untouched.'))return;remove.disabled=true;remove.textContent='Removing…';activity('Removing source',s.space);try{await api('./api/sources/'+s.id,'DELETE');await loadSources();await loadBooks();message('Source removed. Original files were not changed.')}catch(e){message(e.message)}finally{activity('');remove.disabled=false;remove.textContent='Remove'}};actions.append(scan,remove);row.append(head,actions);$('source-list').append(row)}}
async function loadConfig(){if(!currentProfile?.owner)return;const [info,sessions]=await Promise.all([api('./api/server-info'),api('./api/sessions')]);$('config-summary').replaceChildren();for(const [label,value] of [['Server address',info.address],['Owner access',info.configured?'Ready':'Not set'],['Source folders',String(info.sources)],['Active scans',String(info.activeJobs)],['Signed-in sessions',String(info.sessions)]]){const row=element('p');row.append(element('strong',label+': '),document.createTextNode(value));$('config-summary').append(row)}if(info.roots?.length){const roots=element('p','Browsable roots: '+info.roots.map(r=>r.name).join(', '));$('config-summary').append(roots)}$('owner-access-save').textContent=info.configured?'Replace access key':'Set access key';$('session-list').replaceChildren();if(!sessions.length)$('session-list').append(element('p','No active sessions.'));for(const s of sessions){const row=element('article');row.className='source';row.append(element('strong','Session '+s.id),element('p','Created '+new Date(s.created*1000).toLocaleString()),element('p','Expires '+new Date(s.expires*1000).toLocaleString()));$('session-list').append(row)}}
async function start(){currentProfile=await api('./api/me');await loadSources();await loadBooks();$('setup').hidden=true;$('unlock').hidden=true;$('nav').hidden=false;show(page);document.querySelector('[data-page="sources"]').hidden=!currentProfile.owner;document.querySelector('[data-page="config"]').hidden=!currentProfile.owner;window.dispatchEvent(new Event('archivist-ready'))}
async function boot(){try{await start()}catch(e){try{const setup=await api('./setup/status');$('setup').hidden=setup.configured;$('unlock').hidden=!setup.configured}catch(err){message(err.message)}}}
function show(next){page=next;for(const p of ['library','sources','config'])$(p).hidden=p!==next;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===next?'page':'false'));message('');if(next==='config')loadConfig().catch(e=>message(e.message))}
$('setup-form').onsubmit=async e=>{e.preventDefault();try{await api('./setup','POST',{token:$('setup-key').value});$('setup-key').value='';await start()}catch(e){message(e.message)}};
$('login').onsubmit=async e=>{e.preventDefault();try{await api('./unlock','POST',{token:$('key').value});$('key').value='';await start()}catch(e){message(e.message)}};
$('owner-access-form').onsubmit=async e=>{e.preventDefault();const button=$('owner-access-save'),label=button.textContent;button.disabled=true;button.textContent='Saving…';activity('Saving server access key');try{const token=$('owner-access-key').value;await api('./api/owner-access','POST',{token});$('owner-access-key').value='';message('Server access key saved. Use it when connecting the Archivist app.');await loadConfig()}catch(e){message(e.message)}finally{activity('');button.disabled=false;button.textContent=label}};
$('add').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),label=b.textContent;b.disabled=true;b.textContent='Adding…';activity('Adding source folder',$('new-space').value);try{await api('./api/sources','POST',{path:$('path').value,space:$('new-space').value});$('path').value='';await loadSources();message('Folder added. Select Scan / refresh to catalogue it.')}catch(e){message(e.message)}finally{activity('');b.disabled=false;b.textContent=label}};
let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>loadBooks().catch(e=>message(e.message)),180)};$('space').onchange=()=>loadBooks().catch(e=>message(e.message));document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));$('close-player').onclick=()=>{$('audio').pause();$('audio').removeAttribute('src');$('audio').load();$('player').hidden=true};$('audio').onerror=()=>message('Unable to play this file. Check availability and browser codec support.');
$('theme').value=localStorage.getItem('archivist-theme')||'system';function theme(){document.documentElement.style.colorScheme=$('theme').value==='system'?'light dark':$('theme').value;localStorage.setItem('archivist-theme',$('theme').value)}$('theme').onchange=theme;theme();boot();
let folder='',parent='',jobTimer,jobSignature='';
async function browse(p=''){activity('Loading server folders',p||'Available roots');$('picker').hidden=false;$('folder-location').textContent='Loading folders…';$('folder-items').replaceChildren();$('folder-up').disabled=true;$('folder-use').disabled=true;try{const data=await api('./api/folders?path='+encodeURIComponent(p));folder=data.path||'';parent=data.parent||'';$('folder-location').textContent=folder||'Choose a starting folder';$('folder-up').disabled=!parent;$('folder-use').disabled=!folder;const items=Array.isArray(data.folders)?data.folders:[];for(const f of items){const row=element('div'),name=element('strong',f.name),open=element('button','Open'),use=element('button','Use folder');row.className='source';open.type=use.type='button';open.title='Open '+f.path;use.title='Choose '+f.path;open.onclick=()=>browse(f.path);use.onclick=()=>{$('path').value=f.path;$('picker').hidden=true;message('Folder selected. Choose Add folder to add it to Archivist.')};row.append(name,element('p',f.path),open,use);$('folder-items').append(row)}if(!items.length)$('folder-items').append(element('p','No readable folders are available here.'))}catch(e){folder='';parent='';$('folder-location').textContent='Unable to browse server folders';$('folder-items').replaceChildren(element('p',e.message));message(e.message)}finally{activity('')}}
const browseButton=element('button','Browse server folders');browseButton.type='button';browseButton.onclick=()=>browse($('path').value);$('add').append(browseButton);$('folder-up').onclick=()=>browse(parent);$('folder-use').onclick=()=>{$('path').value=folder;$('picker').hidden=true};$('folder-close').onclick=()=>{$('picker').hidden=true};
async function pollJobs(){clearTimeout(jobTimer);try{if(!currentProfile?.owner)return;const jobs=await api('./api/jobs');$('scan-jobs').hidden=jobs.length===0;$('jobs').replaceChildren();for(const j of jobs.slice(0,5)){const row=element('article');row.className='scan-card';const top=element('div');top.className='scan-head';const name=element('strong','Scan '+j.id);const state=element('span',j.state);state.className='status-pill '+(j.state==='failed'?'status-error':j.state==='complete'?'status-ok':'status-active');top.append(name,state);row.append(top);const detail=element('p',j.message||'Preparing scan…');row.append(detail);if(j.state==='queued'||j.state==='running'){const done=Number(j.progress||0),total=Number(j.total||0),pct=total>0?Math.min(100,Math.round(done/total*100)):0;const meta=element('div');meta.className='progress-meta';meta.append(element('span',total?done+' / '+total+' files':'Counting files…'),element('strong',total?pct+'%':'…'));const bar=element('progress');bar.max=total||1;bar.value=total?done:0;row.append(meta,bar)}$('jobs').append(row)}const signature=JSON.stringify(jobs);if(signature!==jobSignature){jobSignature=signature;await loadSources();await loadBooks()}}catch(e){if(!$('unlock').hidden)return;message(e.message)}finally{jobTimer=setTimeout(pollJobs,2000)}}pollJobs();
