let selecting=false;const chosen=new Set();
const groupControls=element('div');groupControls.className='tools';
const choose=element('button','Select files to group'),commit=element('button','Create book'),groupTitle=element('input'),view=element('button','Grouped books');groupTitle.placeholder='Book title';groupTitle.setAttribute('aria-label','Title for grouped book');commit.hidden=true;groupTitle.hidden=true;groupControls.append(choose,groupTitle,commit,view);$('library').insertBefore(groupControls,$('books'));
const grouped=element('section');grouped.hidden=true;$('library').append(grouped);
choose.onclick=()=>{selecting=!selecting;chosen.clear();choose.textContent=selecting?'Cancel selection':'Select files to group';commit.hidden=!selecting;groupTitle.hidden=!selecting;document.querySelectorAll('[data-asset]').forEach(b=>b.removeAttribute('aria-pressed'));message(selecting?'Select audio tracks and editions belonging to one book. Multiple audio files will become one ordered audiobook edition.':'')};
$('books').addEventListener('click',e=>{if(!selecting)return;const b=e.target.closest('[data-asset]');if(!b)return;e.stopImmediatePropagation();e.preventDefault();const id=Number(b.dataset.asset);if(chosen.has(id))chosen.delete(id);else chosen.add(id);b.setAttribute('aria-pressed',String(chosen.has(id)));commit.textContent='Create book ('+chosen.size+')'},true);
commit.onclick=async()=>{if(!confirm('Create this grouping? If selected files already belong to a book, they will be reassigned and earlier edition progress may no longer apply.'))return;commit.disabled=true;try{await api('./api/works/group','POST',{title:groupTitle.value,ids:[...chosen]});choose.click();message('Book created. Original files are unchanged.');await showGroups()}catch(e){message(e.message)}finally{commit.disabled=false}};
async function showGroups(){grouped.hidden=false;grouped.replaceChildren(element('h2','Grouped books'));const items=await api('./api/works?q='+encodeURIComponent($('search').value)+'&space='+encodeURIComponent($('space').value));if(!items.length)grouped.append(element('p','Select related files above to create your first book.'));for(const w of items){const row=element('article');row.className='source';row.append(element('strong',w.title),element('p',w.editions+' editions · '+w.files+' files · '+w.space));const open=element('button','View editions'),split=element('button','Ungroup');open.onclick=async()=>{try{const tracks=await api('./api/works/'+w.id+'/tracks');let detail=row.querySelector('.tracks');if(detail)detail.remove();detail=element('div');detail.className='tracks';let edition=null;for(const t of tracks){if(edition!==t.edition){detail.append(element('h3',t.format+' edition'));edition=t.edition;if(t.format==='Audio'){const resume=element('button','Continue audiobook');resume.onclick=()=>openAudiobook(w.title,tracks,t.edition);detail.append(resume)}}const b=element('button',t.title+(t.available?'':' · Unavailable'));b.disabled=!t.available;b.onclick=()=>{if(t.format==='Audio'){openAudiobook(w.title,tracks,t.edition,t.id)}else window.open('./reader.html?asset='+t.id,'_blank','noopener')};detail.append(b)}row.append(detail)}catch(e){message(e.message)}};split.onclick=async()=>{if(!confirm('Ungroup this book? Its edition playback progress will be removed. Files and source catalogue entries will remain.'))return;try{await api('./api/works/'+w.id,'DELETE');await showGroups()}catch(e){message(e.message)}};row.append(open,split);grouped.append(row)}}
view.onclick=()=>showGroups().catch(e=>message(e.message));
