// One controller owns grouped audiobook playback. No ebook/audio locator conversion.
const playbackAudio=document.getElementById('audio');let listening=null,saveChain=Promise.resolve(),lastSave=0,opening=0;
function remember(){if(!listening||listening.loading)return;const s=listening;s.seconds=Number.isFinite(playbackAudio.currentTime)?playbackAudio.currentTime:0;localStorage.setItem('archivist-progress-'+(currentProfile?.id??0)+'-'+s.edition,JSON.stringify({asset:s.tracks[s.index].id,seconds:s.seconds,revision:s.revision,complete:s.complete}));}
function saveListening(){if(!listening||listening.loading)return saveChain;remember();const session=listening,p={asset:session.tracks[session.index].id,seconds:session.seconds,complete:session.complete};saveChain=saveChain.then(async()=>{if(session.conflict)return;try{const res=await api('/api/editions/'+session.edition+'/progress','PUT',{...p,revision:session.revision});session.revision=res.revision;if(listening===session)remember()}catch(e){session.conflict=true;message('Your place is saved on this device. '+e.message)}});return saveChain;}
async function loadListeningTrack(index,seconds=0){const s=listening;if(!s)return;if(index>=s.tracks.length){s.complete=true;await saveListening();message('Audiobook complete.');return}if(!s.tracks[index].available){message('The next track is unavailable. Playback stopped at your saved place.');return}s.index=index;s.seconds=seconds;s.loading=true;s.complete=false;playbackAudio.src='/api/assets/'+s.tracks[index].id;$('playing-title').textContent=s.title+' · '+s.tracks[index].title;$('player').hidden=false;playbackAudio.onloadedmetadata=()=>{if(listening!==s)return;playbackAudio.currentTime=Number.isFinite(playbackAudio.duration)?Math.min(seconds,playbackAudio.duration):seconds;s.loading=false;remember();playbackAudio.play().catch(()=>message('Press Play to continue. Your browser may not support this audio format.'))};}
async function openAudiobook(title,tracks,edition,explicitAsset){const generation=++opening;await saveListening();playbackAudio.pause();if(generation!==opening)return;const selected=tracks.filter(t=>t.edition===edition&&t.format==='Audio');if(!selected.length)return;let server;try{server=await api('/api/editions/'+edition+'/progress')}catch(e){message(e.message);return}if(generation!==opening)return;let local;try{local=JSON.parse(localStorage.getItem('archivist-progress-'+(currentProfile?.id??0)+'-'+edition)||'null')}catch{};let point=server;if(local&&local.revision===server.revision)point=local;else if(local&&local.revision!==server.revision){message('Loaded the server position. A different local checkpoint remains saved on this device.');localStorage.setItem('archivist-conflict-'+(currentProfile?.id??0)+'-'+edition,JSON.stringify(local));}
 let index=selected.findIndex(t=>t.id===(explicitAsset||point.asset));if(index<0)index=0;listening={edition,title,tracks:selected,index,revision:server.revision,seconds:0,complete:false,loading:true,conflict:false};await loadListeningTrack(index,explicitAsset?0:point.seconds||0);}
playbackAudio.addEventListener('timeupdate',()=>{if(Date.now()-lastSave>5000){lastSave=Date.now();saveListening()}});playbackAudio.addEventListener('pause',()=>saveListening());playbackAudio.addEventListener('seeked',()=>saveListening());playbackAudio.addEventListener('ended',async()=>{if(!listening)return;await saveListening();await loadListeningTrack(listening.index+1)});document.addEventListener('visibilitychange',()=>{if(document.hidden)saveListening()});window.addEventListener('pagehide',remember);
document.getElementById('close-player').addEventListener('click',()=>{saveListening();listening=null;playbackAudio.onloadedmetadata=null},true);
// Switching to a raw file ends the grouped session before the other handler sets src.
document.getElementById('books').addEventListener('click',()=>{if(typeof selecting!=='undefined'&&selecting)return;saveListening();listening=null;playbackAudio.onloadedmetadata=null},true);
