// Generated by scripts/sync-speech-focus.cjs; edit mobile/speechFocus.ts.
function detectBubbleRegion(
  pixels                  ,
  width       ,
  height       ,
  tapX       ,
  tapY       ,
)                        {
  // Reject malformed or oversized inputs before allocating working buffers.
  if(!Number.isInteger(width)||!Number.isInteger(height)||width<8||height<8||
    width*height>1048576||!Number.isFinite(tapX)||!Number.isFinite(tapY)||
    tapX<0||tapY<0||tapX>=width||tapY>=height||pixels.length<width*height*4)return null;
  const lum=(r       ,g       ,b       )=>0.2126*r+0.7152*g+0.0722*b;
  const index=(x       ,y       )=>(y*width+x)*4;
  const tx=Math.max(0,Math.min(width-1,Math.round(tapX)));
  const ty=Math.max(0,Math.min(height-1,Math.round(tapY)));

  let seedX=tx,seedY=ty,seedLum=-1;
  const radius=Math.max(5,Math.min(22,Math.round(Math.min(width,height)*0.035)));
  for(let dy=-radius;dy<=radius;dy++){
    const y=ty+dy;if(y<0||y>=height)continue;
    for(let dx=-radius;dx<=radius;dx++){
      const x=tx+dx;if(x<0||x>=width||dx*dx+dy*dy>radius*radius)continue;
      const p=index(x,y);if(pixels[p+3]<180)continue;
      const value=lum(pixels[p],pixels[p+1],pixels[p+2]);
      const distance=Math.sqrt(dx*dx+dy*dy);
      const score=value-distance*1.4;
      if(score>seedLum){seedLum=score;seedX=x;seedY=y;}
    }
  }
  const sp=index(seedX,seedY);
  const sr=pixels[sp],sg=pixels[sp+1],sb=pixels[sp+2],baseLum=lum(sr,sg,sb);
  if(baseLum<115)return null;

  const total=width*height;
  const visited=new Uint8Array(total);
  const queue=new Int32Array(total);
  const tolerance=95*95;
  const minLum=Math.max(75,baseLum-95);
  const maxArea=Math.max(96,Math.floor(total*0.30));
  let head=0,tail=0,area=0;
  let left=width,top=height,right=-1,bottom=-1;
  const enqueue=(pos       )=>{if(!visited[pos]){visited[pos]=1;queue[tail++]=pos;}};
  enqueue(seedY*width+seedX);

  while(head<tail){
    const pos=queue[head++];
    const x=pos%width,y=(pos/width)|0,p=pos*4;
    const r=pixels[p],g=pixels[p+1],b=pixels[p+2];
    const dr=r-sr,dg=g-sg,db=b-sb;
    if(pixels[p+3]<160||lum(r,g,b)<minLum||dr*dr+dg*dg+db*db>tolerance)continue;
    visited[pos]=2;area++;
    if(area>maxArea)return null;
    if(x<left)left=x;if(x>right)right=x;if(y<top)top=y;if(y>bottom)bottom=y;
    if(x>0)enqueue(pos-1);
    if(x+1<width)enqueue(pos+1);
    if(y>0)enqueue(pos-width);
    if(y+1<height)enqueue(pos+width);
  }

  if(area<Math.max(28,total*0.00035)||right<=left||bottom<=top)return null;
  const boxArea=(right-left+1)*(bottom-top+1);
  if(boxArea>total*0.32||(right-left)>width*0.88||(bottom-top)>height*0.78)return null;

  const pad=Math.max(2,Math.round(Math.min(right-left+1,bottom-top+1)*0.045));
  left=Math.max(0,left-pad);right=Math.min(width-1,right+pad);
  top=Math.max(0,top-pad);bottom=Math.min(height-1,bottom+pad);
  // Flood the *outside* of the selected component. Enclosed holes are ink
  // (letters/counters) and must remain opaque; concavities open to the page
  // remain outside. Unlike a row envelope this preserves split row spans.
  head=0;tail=0;
  const outside=(pos       )=>{
    if(visited[pos]!==2&&visited[pos]!==3){visited[pos]=3;queue[tail++]=pos;}
  };
  for(let x=left;x<=right;x++){outside(top*width+x);outside(bottom*width+x);}
  for(let y=top;y<=bottom;y++){outside(y*width+left);outside(y*width+right);}
  while(head<tail){
    const pos=queue[head++],x=pos%width,y=(pos/width)|0;
    if(x>left)outside(pos-1);if(x<right)outside(pos+1);
    if(y>top)outside(pos-width);if(y<bottom)outside(pos+width);
  }
  // Round dilation includes outline ink without bridging a whole concavity.
  // Bound the mask to the crop; no full-resolution source allocations.
  const maskW=right-left+1,maskH=bottom-top+1;
  const mask=new Uint8Array(maskW*maskH);
  const reaches=Array.from({length:pad*2+1},(_,i)=>Math.floor(Math.sqrt(pad*pad-(i-pad)*(i-pad))));
  // Dilate runs, not individual pixels: one fill per span/offset keeps large
  // balloon interiors from multiplying work by every pixel in the crop.
  for(let y=top;y<=bottom;y++){
    let x=left;
    while(x<=right){
      while(x<=right&&visited[y*width+x]===3)x++;
      const runStart=x;
      while(x<=right&&visited[y*width+x]!==3)x++;
      if(x===runStart)continue;
      const runEnd=x-1;
      for(let dy=-pad;dy<=pad;dy++){
        const yy=y+dy;if(yy<top||yy>bottom)continue;
        const reach=reaches[dy+pad];
        const start=Math.max(left,runStart-reach),end=Math.min(right,runEnd+reach);
        mask.fill(1,(yy-top)*maskW+start-left,(yy-top)*maskW+end-left+1);
      }
    }
  }
  const rows                                           =[];
  for(let y=0;y<maskH;y++){
    let x=0;
    while(x<maskW){
      while(x<maskW&&!mask[y*maskW+x])x++;
      const start=x;
      while(x<maskW&&mask[y*maskW+x])x++;
      if(x>start)rows.push({y:y+top,left:start+left,right:x-1+left});
    }
  }
  return {left,top,right,bottom,area,rows};
}

function installSpeechFocus(detector                          ){
  let overlay    =null;
  let generation=0;
  let animation    =null;
  let closing=false;
  let origin='none';
  let previousFocus    =null;
  const cache=new Map            ();

  const reduced=()=>typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
  function cancel(){
    generation++;
    animation?.cancel();animation=null;closing=false;
    if(overlay){overlay.remove();overlay=null;}
  }
  function close(){
    if(!overlay||closing)return;
    const button=overlay,token=++generation;
    closing=true;
    const current=typeof getComputedStyle==='function'?getComputedStyle(button).transform:'none';
    animation?.cancel();animation=null;
    const finish=()=>{
      if(token!==generation||button!==overlay)return;
      cancel();
      if(previousFocus?.isConnected)previousFocus.focus?.({preventScroll:true});
    };
    if(reduced()||typeof button.animate!=='function'){finish();return;}
    animation=button.animate([{transform:current,opacity:1},{transform:origin,opacity:0.85}],
      {duration:260,easing:'cubic-bezier(.4,0,.2,1)',fill:'both'});
    animation.onfinish=finish;
  }

  function regionFor(img    ,clientX       ,clientY       ,key       ){
    const rect=img.getBoundingClientRect();
    if(!rect.width||!rect.height||!img.naturalWidth||!img.naturalHeight)return null;
    const maxAnalysis=520;
    const scale=Math.min(1,maxAnalysis/Math.max(img.naturalWidth,img.naturalHeight));
    const width=Math.max(8,Math.round(img.naturalWidth*scale));
    const height=Math.max(8,Math.round(img.naturalHeight*scale));
    const x=(clientX-rect.left)/rect.width*width;
    const y=(clientY-rect.top)/rect.height*height;
    if(x<0||y<0||x>=width||y>=height)return null;
    // Exact analysis-pixel taps cannot collide across adjacent bubbles.
    // Source identity prevents stale crops when a reader reuses a page number.
    const bucket=JSON.stringify([key,img.currentSrc||img.src,img.naturalWidth,img.naturalHeight,Math.floor(x),Math.floor(y)]);
    if(cache.has(bucket))return {region:cache.get(bucket),rect,width,height,bucket};
    const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;
    const ctx=canvas.getContext('2d',{willReadFrequently:true});
    if(!ctx)return null;
    ctx.drawImage(img,0,0,width,height);
    let data;
    try{data=ctx.getImageData(0,0,width,height).data;}catch{return null;}
    const region=detector(data,width,height,x,y);
    if(!region)return null;
    cache.set(bucket,region);
    if(cache.size>24){const oldest=cache.keys().next().value;if(oldest)cache.delete(oldest);}
    return {region,rect,width,height,bucket};
  }

  function focus(img    ,clientX       ,clientY       ,key='page'){
    if(overlay&&!closing){close();return true;}
    if(closing)cancel();
    const token=++generation;
    const found=regionFor(img,clientX,clientY,key);
    if(!found||token!==generation)return false;
    const {region,rect,width,height}=found;
    const sx=img.naturalWidth/width,sy=img.naturalHeight/height;
    const sourceX=region.left*sx,sourceY=region.top*sy;
    const sourceW=(region.right-region.left+1)*sx,sourceH=(region.bottom-region.top+1)*sy;
    if(sourceW<12||sourceH<12)return false;

    const maxPixels=1600;
    const outputScale=Math.min(1,maxPixels/Math.max(sourceW,sourceH));
    const outW=Math.max(1,Math.round(sourceW*outputScale));
    const outH=Math.max(1,Math.round(sourceH*outputScale));
    const canvas=document.createElement('canvas');canvas.width=outW;canvas.height=outH;
    const ctx=canvas.getContext('2d');if(!ctx)return false;

    const path=new Path2D();
    const xScale=outW/(region.right-region.left+1);
    const yScale=outH/(region.bottom-region.top+1);
    const rows=region.rows;
    if(rows.length<2)return false;
    // Each span is part of one binary silhouette. Multiple spans on a row
    // preserve concavities instead of joining through unrelated artwork.
    for(const row of rows)path.rect((row.left-region.left)*xScale,(row.y-region.top)*yScale,
      (row.right-row.left+1)*xScale,yScale);
    ctx.save();ctx.clip(path);
    ctx.drawImage(img,sourceX,sourceY,sourceW,sourceH,0,0,outW,outH);
    ctx.restore();

    const displayLeft=rect.left+(region.left/width)*rect.width;
    const displayTop=rect.top+(region.top/height)*rect.height;
    const displayW=((region.right-region.left+1)/width)*rect.width;
    const displayH=((region.bottom-region.top+1)/height)*rect.height;
    const button=document.createElement('button');
    button.type='button';button.className='speech-focus-overlay';
    button.setAttribute('aria-label','Close enlarged speech bubble');
    // Read CSS safe-area insets without changing the reader's scroll/layout.
    button.style.padding='env(safe-area-inset-top, 0px) env(safe-area-inset-right, 0px) env(safe-area-inset-bottom, 0px) env(safe-area-inset-left, 0px)';
    document.body.append(button);
    const inset=typeof getComputedStyle==='function'?getComputedStyle(button):null;
    const topInset=parseFloat(inset?.paddingTop||'0')||0,bottomInset=parseFloat(inset?.paddingBottom||'0')||0;
    const leftInset=parseFloat(inset?.paddingLeft||'0')||0,rightInset=parseFloat(inset?.paddingRight||'0')||0;
    button.style.padding='0';
    const viewport=typeof window!=='undefined'?window.visualViewport:null;
    const vw=viewport?.width||innerWidth,vh=viewport?.height||innerHeight;
    const vx=(viewport?.offsetLeft||0)+leftInset+16,vy=(viewport?.offsetTop||0)+topInset+16;
    const availableW=Math.max(1,vw-leftInset-rightInset-32),availableH=Math.max(1,vh-topInset-bottomInset-32);
    const ratio=displayW/displayH;
    const targetW=Math.min(availableW,availableH*ratio,Math.max(displayW*2.15,220));
    const targetH=targetW/ratio;
    // Stay near the source, moving only as much as readability/edges require.
    const targetLeft=Math.max(vx,Math.min(vx+availableW-targetW,displayLeft+(displayW-targetW)/2));
    const targetTop=Math.max(vy,Math.min(vy+availableH-targetH,displayTop+(displayH-targetH)/2));
    origin=`translate(${displayLeft-targetLeft}px, ${displayTop-targetTop}px) scale(${displayW/targetW}, ${displayH/targetH})`;
    button.style.left=targetLeft+'px';button.style.top=targetTop+'px';
    button.style.width=targetW+'px';button.style.height=targetH+'px';
    button.style.transformOrigin='0 0';button.style.transition='none';button.style.opacity='1';
    canvas.style.width='100%';canvas.style.height='100%';button.append(canvas);
    button.onclick=close;button.onkeydown=(event    )=>{if(event.key==='Escape'||event.key==='Enter'||event.key===' '){event.preventDefault();close();}};
    previousFocus=document.activeElement;overlay=button;button.classList.add('open');button.focus({preventScroll:true});
    if(!reduced()&&typeof button.animate==='function'){
      animation=button.animate([{transform:origin,opacity:.85},{transform:'none',opacity:1}],
        {duration:340,easing:'cubic-bezier(.2,.72,.2,1)',fill:'both'});
    }
    return true;
  }

  document.addEventListener('pointerdown',(event    )=>{
    if(overlay && !overlay.contains(event.target))close();
  },true);
  // Geometry becomes stale on page motion, fold/rotation or pinch. Remove
  // immediately instead of animating back to a location that has moved.
  if(typeof window!=='undefined'){
    window.addEventListener('resize',cancel);
    window.addEventListener('scroll',cancel,{passive:true});
    window.visualViewport?.addEventListener('resize',cancel);
    window.visualViewport?.addEventListener('scroll',cancel);
  }
  document.addEventListener('touchstart',(event    )=>{if(event.touches.length>1)cancel();},{passive:true,capture:true});
  return {focus,close,cancel,isActive:()=>!!overlay&&!closing};
}


export function createSpeechFocusController(){return installSpeechFocus(detectBubbleRegion);}
