const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn,execFileSync}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'archivist-browser-')),media=path.join(temp,'media'),epub=path.join(temp,'epub');
let server,browser;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 fs.mkdirSync(media);fs.mkdirSync(path.join(epub,'META-INF'),{recursive:true});fs.mkdirSync(path.join(epub,'OPS'));
 fs.writeFileSync(path.join(epub,'META-INF/container.xml'),'<container><rootfiles><rootfile full-path="OPS/book.opf"/></rootfiles></container>');
 fs.writeFileSync(path.join(epub,'OPS/book.opf'),'<package><metadata><title>Smoke EPUB</title></metadata><manifest><item id="a" href="a.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="a"/></spine></package>');
 fs.writeFileSync(path.join(epub,'OPS/a.xhtml'),'<html><body><h1>Chapter heading</h1><p>Hello <em>reader</em>.</p><table><tr><td>Table content</td></tr></table><img src="pixel.png"/><script>window.stolen=true</script></body></html>');
 fs.writeFileSync(path.join(epub,'OPS/pixel.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64'));
 execFileSync('zip',['-qr',path.join(media,'Smoke.epub'),'.'],{cwd:epub});
 const parts=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 400] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
 const stream='BT /F1 20 Tf 20 350 Td (Archivist PDF test) Tj ET';parts.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
 let pdf='%PDF-1.4\n',offsets=[0];parts.forEach((p,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${p}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Root 1 0 R /Size 6 >>\nstartxref\n${xref}\n%%EOF\n`;fs.writeFileSync(path.join(media,'Smoke.pdf'),pdf);
 const base='http://127.0.0.1:15056';let output='';
 server=spawn('/tmp/archivist-batch-test',['-data',path.join(temp,'db'),'-listen','127.0.0.1:15056']);server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
 for(let n=0;n<100&&!output.includes('Local access key:');n++)await delay(100);
 const token=/Local access key: ([a-f0-9]+)/.exec(output)?.[1];assert(token,output);
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1200,height:850}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#key').fill(token);await page.locator('#login button').click();await page.locator('#library').waitFor({state:'visible'});
 const headers={'X-Archivist-Action':'1'};
 assert.equal((await context.request.post(base+'/api/sources',{headers,data:{path:media,space:'Smoke'}})).status(),200);
 await context.request.post(base+'/api/sources/1/scan',{headers});
 let books=[];for(let n=0;n<100;n++){books=await(await context.request.get(base+'/api/books')).json();if(books.length===2)break;await delay(100);}assert.equal(books.length,2);
 const ebook=books.find(b=>b.format==='Ebook'),document=books.find(b=>b.format==='PDF');
 await page.goto(base+'/reader.html?asset='+ebook.id);await page.locator('#reading h1').waitFor();assert.equal(await page.locator('#reading em').textContent(),'reader');assert.equal(await page.locator('#reading table').count(),1);assert.equal(await page.evaluate(()=>window.stolen),undefined);
 await page.waitForFunction(()=>document.querySelector('#reading img')?.naturalWidth>0);
 await page.screenshot({path:'/tmp/archivist-reader-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/archivist-reader-mobile.png'});
 await page.goto(base+'/reader.html?asset='+document.id);await page.locator('#reading canvas').waitFor();await page.waitForFunction(()=>document.querySelector('#reader-status').textContent==='');
 assert(await page.locator('#reading canvas').evaluate(c=>c.width>0&&c.height>0));
 assert.deepEqual(errors,[]);
 console.log('PASS: browser login, scan, EPUB semantic markup/image/no scripts, desktop/mobile screenshots and PDF canvas');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));}fs.rmSync(temp,{recursive:true,force:true});});
